import type { Metadata } from 'next'
import './font.css'
import './globals.css'

export const metadata: Metadata = {
  title: 'LLMC',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        
        {children}
      </body>
    </html>
  )
}
